/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Trainify API
 * API para solução escalável para controle de planos de treino e acompanhamento físico.
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch";
/**
 * Sessão iniciada com sucesso
 */
export type StartSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  startedAt: string | null;
  completedAt: string | null;
};

export type StartSession400IssuesItem = {
  field: string;
  message: string;
};

/**
 * Dados inválidos
 */
export type StartSession400 = {
  statusCode: number;
  code: string;
  message: string;
  issues: StartSession400IssuesItem[];
};

/**
 * Sessão inválida ou ausente
 */
export type StartSession401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Plano ou Dia de treino não encontrado
 */
export type StartSession404 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Sessão já iniciada para o dia informado
 */
export type StartSession409 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type StartSession500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type UpdateSessionDataBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

/**
 * Sessão atualizada com sucesso
 */
export type UpdateSessionData200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  startedAt: string | null;
  completedAt: string | null;
};

export type UpdateSessionData400IssuesItem = {
  field: string;
  message: string;
};

/**
 * Dados inválidos
 */
export type UpdateSessionData400 = {
  statusCode: number;
  code: string;
  message: string;
  issues: UpdateSessionData400IssuesItem[];
};

/**
 * Sessão inválida ou ausente
 */
export type UpdateSessionData401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Plano ou Sessão de treino não encontrado(a)
 */
export type UpdateSessionData404 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type UpdateSessionData500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type CreateWorkoutPlanDataBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanDataBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanDataBodyWorkoutDaysItemWeekDay];

export const CreateWorkoutPlanDataBodyWorkoutDaysItemWeekDay = {
  monday: "monday",
  tuesday: "tuesday",
  wednesday: "wednesday",
  thursday: "thursday",
  friday: "friday",
  saturday: "saturday",
  sunday: "sunday",
} as const;

export type CreateWorkoutPlanDataBodyWorkoutDaysItemExercisesItem = {
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  /** @minimum 0 */
  order: number;
  youtubeVideoId?: string | null;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 0 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlanDataBodyWorkoutDaysItem = {
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  weekDay: CreateWorkoutPlanDataBodyWorkoutDaysItemWeekDay;
  isRest?: boolean;
  coverImageUrl?: string | "";
  /** @minimum 0 */
  estimatedDurationInSeconds: number;
  exercises: CreateWorkoutPlanDataBodyWorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlanDataBody = {
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  isActive?: boolean;
  workoutDays: CreateWorkoutPlanDataBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlanData201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanData201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanData201WorkoutDaysItemWeekDay];

export const CreateWorkoutPlanData201WorkoutDaysItemWeekDay = {
  monday: "monday",
  tuesday: "tuesday",
  wednesday: "wednesday",
  thursday: "thursday",
  friday: "friday",
  saturday: "saturday",
  sunday: "sunday",
} as const;

export type CreateWorkoutPlanData201WorkoutDaysItemExercisesItem = {
  /**
   * @minLength 1
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$
   */
  id: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  /** @minimum 0 */
  order: number;
  youtubeVideoId?: string | null;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 0 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlanData201WorkoutDaysItem = {
  /**
   * @minLength 1
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$
   */
  id: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  weekDay: CreateWorkoutPlanData201WorkoutDaysItemWeekDay;
  isRest: boolean;
  coverImageUrl?: string;
  /** @minimum 0 */
  estimatedDurationInSeconds: number;
  exercises: CreateWorkoutPlanData201WorkoutDaysItemExercisesItem[];
};

/**
 * Plano de treino criado com sucesso
 */
export type CreateWorkoutPlanData201 = {
  /**
   * @minLength 1
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$
   */
  id: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  workoutDays: CreateWorkoutPlanData201WorkoutDaysItem[];
};

export type CreateWorkoutPlanData400IssuesItem = {
  field: string;
  message: string;
};

/**
 * Dados inválidos
 */
export type CreateWorkoutPlanData400 = {
  statusCode: number;
  code: string;
  message: string;
  issues: CreateWorkoutPlanData400IssuesItem[];
};

/**
 * Sessão inválida ou ausente
 */
export type CreateWorkoutPlanData401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Plano de treino não encontrado
 */
export type CreateWorkoutPlanData404 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type CreateWorkoutPlanData500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type GetAllWorkoutPlansData200ItemWorkoutDaysItemWeekDay =
  (typeof GetAllWorkoutPlansData200ItemWorkoutDaysItemWeekDay)[keyof typeof GetAllWorkoutPlansData200ItemWorkoutDaysItemWeekDay];

export const GetAllWorkoutPlansData200ItemWorkoutDaysItemWeekDay = {
  monday: "monday",
  tuesday: "tuesday",
  wednesday: "wednesday",
  thursday: "thursday",
  friday: "friday",
  saturday: "saturday",
  sunday: "sunday",
} as const;

export type GetAllWorkoutPlansData200ItemWorkoutDaysItemExercisesItem = {
  /**
   * @minLength 1
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$
   */
  id: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  /** @minimum 0 */
  order: number;
  youtubeVideoId?: string | null;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 0 */
  restTimeInSeconds: number;
};

export type GetAllWorkoutPlansData200ItemWorkoutDaysItem = {
  /**
   * @minLength 1
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$
   */
  id: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  weekDay: GetAllWorkoutPlansData200ItemWorkoutDaysItemWeekDay;
  isRest: boolean;
  coverImageUrl?: string;
  /** @minimum 0 */
  estimatedDurationInSeconds: number;
  exercises: GetAllWorkoutPlansData200ItemWorkoutDaysItemExercisesItem[];
};

export type GetAllWorkoutPlansData200Item = {
  /**
   * @minLength 1
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$
   */
  id: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  workoutDays: GetAllWorkoutPlansData200ItemWorkoutDaysItem[];
};

/**
 * Sessão inválida ou ausente
 */
export type GetAllWorkoutPlansData401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type GetAllWorkoutPlansData500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type GetWorkoutPlanDetailsdData200WorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlanDetailsdData200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlanDetailsdData200WorkoutDaysItemWeekDay];

export const GetWorkoutPlanDetailsdData200WorkoutDaysItemWeekDay = {
  monday: "monday",
  tuesday: "tuesday",
  wednesday: "wednesday",
  thursday: "thursday",
  friday: "friday",
  saturday: "saturday",
  sunday: "sunday",
} as const;

export type GetWorkoutPlanDetailsdData200WorkoutDaysItem = {
  id: string;
  weekDay: GetWorkoutPlanDetailsdData200WorkoutDaysItemWeekDay;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

/**
 * Plano de treino encontrado
 */
export type GetWorkoutPlanDetailsdData200 = {
  id: string;
  name: string;
  workoutDays: GetWorkoutPlanDetailsdData200WorkoutDaysItem[];
};

/**
 * Sessão inválida ou ausente
 */
export type GetWorkoutPlanDetailsdData401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Plano de treino não encontrado
 */
export type GetWorkoutPlanDetailsdData404 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type GetWorkoutPlanDetailsdData500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type GetWorkoutPlanDayDetailsData200WeekDay =
  (typeof GetWorkoutPlanDayDetailsData200WeekDay)[keyof typeof GetWorkoutPlanDayDetailsData200WeekDay];

export const GetWorkoutPlanDayDetailsData200WeekDay = {
  monday: "monday",
  tuesday: "tuesday",
  wednesday: "wednesday",
  thursday: "thursday",
  friday: "friday",
  saturday: "saturday",
  sunday: "sunday",
} as const;

export type GetWorkoutPlanDayDetailsData200ExercisesItem = {
  id: string;
  name: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
  youtubeVideoId: string | null;
  order: number;
  workoutDayId: string;
};

export type GetWorkoutPlanDayDetailsData200SessionsItem = {
  id: string;
  workoutDayId: string;
  startedAt: string | null;
  completedAt: string | null;
};

/**
 * Dia do plano retornado com sucesso
 */
export type GetWorkoutPlanDayDetailsData200 = {
  id: string;
  name: string;
  isRest: boolean;
  coverImageUrl: string | null;
  estimatedDurationInSeconds: number;
  weekDay: GetWorkoutPlanDayDetailsData200WeekDay;
  exercises: GetWorkoutPlanDayDetailsData200ExercisesItem[];
  sessions: GetWorkoutPlanDayDetailsData200SessionsItem[];
};

/**
 * Sessão inválida ou ausente
 */
export type GetWorkoutPlanDayDetailsData401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Plano ou Dia de treino não encontrado
 */
export type GetWorkoutPlanDayDetailsData404 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type GetWorkoutPlanDayDetailsData500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type GetSessionSets200Item = {
  id: string;
  sessionId: string;
  exerciseId: string;
  setNumber: number;
  completedAt: string;
};

/**
 * Sessão inválida ou ausente
 */
export type GetSessionSets401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Sessão não encontrada
 */
export type GetSessionSets404 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type GetSessionSets500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type CompleteSetBody = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  setNumber: number;
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  totalSetsInWorkout: number;
};

export type CompleteSet200Set = {
  id: string;
  sessionId: string;
  exerciseId: string;
  setNumber: number;
  completedAt: string;
};

/**
 * Série concluída com sucesso
 */
export type CompleteSet200 = {
  set: CompleteSet200Set;
  autoCompleted: boolean;
};

export type CompleteSet400IssuesItem = {
  field: string;
  message: string;
};

/**
 * Dados inválidos
 */
export type CompleteSet400 = {
  statusCode: number;
  code: string;
  message: string;
  issues: CompleteSet400IssuesItem[];
};

/**
 * Sessão inválida ou ausente
 */
export type CompleteSet401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Sessão de treino não encontrada
 */
export type CompleteSet404 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type CompleteSet500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type UndoSetBody = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  setNumber: number;
};

export type UndoSet400IssuesItem = {
  field: string;
  message: string;
};

/**
 * Dados inválidos
 */
export type UndoSet400 = {
  statusCode: number;
  code: string;
  message: string;
  issues: UndoSet400IssuesItem[];
};

/**
 * Sessão inválida ou ausente
 */
export type UndoSet401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Sessão de treino não encontrada
 */
export type UndoSet404 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type UndoSet500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type GetHomeData200TodayWorkoutDay = {
  workoutPlanId: string;
  id: string;
  name: string;
  isRest: boolean;
  weekDay:
    | "monday"
    | "tuesday"
    | "wednesday"
    | "thursday"
    | "friday"
    | "saturday"
    | "sunday";
  estimatedDurationInSeconds: number;
  coverImageUrl: string | null;
  exercisesCount: number;
} | null;

export type GetHomeData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
} | null;

/**
 * Dados da tela Home carregados com sucesso
 */
export type GetHomeData200 = {
  activeWorkoutPlanId: string;
  todayWorkoutDay: GetHomeData200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHomeData200ConsistencyByDay;
};

/**
 * Data inválida
 */
export type GetHomeData400 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Sessão inválida ou ausente
 */
export type GetHomeData401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type GetHomeData500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type GetStatsDataParams = {
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  from: string;
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  to: string;
};

export type GetStatsData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

/**
 * Métricas carregadas com sucesso
 */
export type GetStatsData200 = {
  workoutStreak: number;
  consistencyByDay: GetStatsData200ConsistencyByDay;
  completedWorkoutsCount: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
};

/**
 * Parâmetros de data inválidos
 */
export type GetStatsData400 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Sessão inválida ou ausente
 */
export type GetStatsData401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type GetStatsData500 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Dados de treino do usuário
 */
export type GetMe200 = {
  /** ID do usuário */
  userId: string;
  /** Nome do usuário */
  userName: string;
  /** Peso do usuário em gramas */
  weightInGrams: number;
  /** Altura do usuário em centímetros */
  heightInCentimeters: number;
  /** Idade do usuário em anos */
  age: number;
  /** Percentual de gordura corporal (0 a 1) */
  bodyFatPercentage: number;
} | null;

/**
 * Sessão inválida ou ausente
 */
export type GetMe401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type GetMe500 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Dados de treino do usuário
 */
export type UpsertTrainDataBody = {
  /**
   * Peso do usuário em gramas
   * @maximum 9007199254740991
   * @exclusiveMinimum 0
   */
  weightInGrams: number;
  /**
   * Altura do usuário em centímetros
   * @maximum 9007199254740991
   * @exclusiveMinimum 0
   */
  heightInCentimeters: number;
  /**
   * Idade do usuário em anos
   * @minimum 1
   * @maximum 120
   */
  age: number;
  /**
   * Percentual de gordura corporal (0 a 1, onde 1 = 100%)
   * @minimum 0
   * @maximum 1
   */
  bodyFatPercentage: number;
};

/**
 * Dados de treino salvos com sucesso
 */
export type UpsertTrainData200 = {
  /** ID do usuário */
  userId: string;
  /** Nome do usuário */
  userName: string;
  /** Peso do usuário em gramas */
  weightInGrams: number;
  /** Altura do usuário em centímetros */
  heightInCentimeters: number;
  /** Idade do usuário em anos */
  age: number;
  /** Percentual de gordura corporal (0 a 1) */
  bodyFatPercentage: number;
} | null;

export type UpsertTrainData400IssuesItem = {
  field: string;
  message: string;
};

/**
 * Dados inválidos
 */
export type UpsertTrainData400 = {
  statusCode: number;
  code: string;
  message: string;
  issues: UpsertTrainData400IssuesItem[];
};

/**
 * Sessão inválida ou ausente
 */
export type UpsertTrainData401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type UpsertTrainData500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type ChatBodyMessagesItemRole =
  (typeof ChatBodyMessagesItemRole)[keyof typeof ChatBodyMessagesItemRole];

export const ChatBodyMessagesItemRole = {
  user: "user",
  assistant: "assistant",
} as const;

export type ChatBodyMessagesItemPartsItem = {
  type: string;
  text?: string;
  [key: string]: unknown;
};

export type ChatBodyMessagesItem = {
  id: string;
  role: ChatBodyMessagesItemRole;
  parts: ChatBodyMessagesItemPartsItem[];
};

export type ChatBody = {
  messages: ChatBodyMessagesItem[];
};

/**
 * @summary Inicia uma nova sessão de treino
 */
export type startSessionResponse201 = {
  data: StartSession201;
  status: 201;
};

export type startSessionResponse400 = {
  data: StartSession400;
  status: 400;
};

export type startSessionResponse401 = {
  data: StartSession401;
  status: 401;
};

export type startSessionResponse404 = {
  data: StartSession404;
  status: 404;
};

export type startSessionResponse409 = {
  data: StartSession409;
  status: 409;
};

export type startSessionResponse500 = {
  data: StartSession500;
  status: 500;
};

export type startSessionResponseSuccess = startSessionResponse201 & {
  headers: Headers;
};
export type startSessionResponseError = (
  | startSessionResponse400
  | startSessionResponse401
  | startSessionResponse404
  | startSessionResponse409
  | startSessionResponse500
) & {
  headers: Headers;
};

export type startSessionResponse =
  | startSessionResponseSuccess
  | startSessionResponseError;

export const getStartSessionUrl = (id: string, dayId: string) => {
  return `/trainify/api/v1/workout-plans/${id}/days/${dayId}/sessions`;
};

export const startSession = async (
  id: string,
  dayId: string,
  options?: RequestInit,
): Promise<startSessionResponse> => {
  return customFetch<startSessionResponse>(getStartSessionUrl(id, dayId), {
    ...options,
    method: "POST",
  });
};

/**
 * @summary Atualiza uma sessão de treino
 */
export type updateSessionDataResponse200 = {
  data: UpdateSessionData200;
  status: 200;
};

export type updateSessionDataResponse400 = {
  data: UpdateSessionData400;
  status: 400;
};

export type updateSessionDataResponse401 = {
  data: UpdateSessionData401;
  status: 401;
};

export type updateSessionDataResponse404 = {
  data: UpdateSessionData404;
  status: 404;
};

export type updateSessionDataResponse500 = {
  data: UpdateSessionData500;
  status: 500;
};

export type updateSessionDataResponseSuccess = updateSessionDataResponse200 & {
  headers: Headers;
};
export type updateSessionDataResponseError = (
  | updateSessionDataResponse400
  | updateSessionDataResponse401
  | updateSessionDataResponse404
  | updateSessionDataResponse500
) & {
  headers: Headers;
};

export type updateSessionDataResponse =
  | updateSessionDataResponseSuccess
  | updateSessionDataResponseError;

export const getUpdateSessionDataUrl = (
  id: string,
  dayId: string,
  sessionId: string,
) => {
  return `/trainify/api/v1/workout-plans/${id}/days/${dayId}/sessions/${sessionId}`;
};

export const updateSessionData = async (
  id: string,
  dayId: string,
  sessionId: string,
  updateSessionDataBody: UpdateSessionDataBody,
  options?: RequestInit,
): Promise<updateSessionDataResponse> => {
  return customFetch<updateSessionDataResponse>(
    getUpdateSessionDataUrl(id, dayId, sessionId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateSessionDataBody),
    },
  );
};

/**
 * @summary Cria um novo plano de treino
 */
export type createWorkoutPlanDataResponse201 = {
  data: CreateWorkoutPlanData201;
  status: 201;
};

export type createWorkoutPlanDataResponse400 = {
  data: CreateWorkoutPlanData400;
  status: 400;
};

export type createWorkoutPlanDataResponse401 = {
  data: CreateWorkoutPlanData401;
  status: 401;
};

export type createWorkoutPlanDataResponse404 = {
  data: CreateWorkoutPlanData404;
  status: 404;
};

export type createWorkoutPlanDataResponse500 = {
  data: CreateWorkoutPlanData500;
  status: 500;
};

export type createWorkoutPlanDataResponseSuccess =
  createWorkoutPlanDataResponse201 & {
    headers: Headers;
  };
export type createWorkoutPlanDataResponseError = (
  | createWorkoutPlanDataResponse400
  | createWorkoutPlanDataResponse401
  | createWorkoutPlanDataResponse404
  | createWorkoutPlanDataResponse500
) & {
  headers: Headers;
};

export type createWorkoutPlanDataResponse =
  | createWorkoutPlanDataResponseSuccess
  | createWorkoutPlanDataResponseError;

export const getCreateWorkoutPlanDataUrl = () => {
  return `/trainify/api/v1/workout-plans`;
};

export const createWorkoutPlanData = async (
  createWorkoutPlanDataBody: CreateWorkoutPlanDataBody,
  options?: RequestInit,
): Promise<createWorkoutPlanDataResponse> => {
  return customFetch<createWorkoutPlanDataResponse>(
    getCreateWorkoutPlanDataUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(createWorkoutPlanDataBody),
    },
  );
};

/**
 * @summary Retorna todos os planos de treino
 */
export type getAllWorkoutPlansDataResponse200 = {
  data: GetAllWorkoutPlansData200Item[];
  status: 200;
};

export type getAllWorkoutPlansDataResponse401 = {
  data: GetAllWorkoutPlansData401;
  status: 401;
};

export type getAllWorkoutPlansDataResponse500 = {
  data: GetAllWorkoutPlansData500;
  status: 500;
};

export type getAllWorkoutPlansDataResponseSuccess =
  getAllWorkoutPlansDataResponse200 & {
    headers: Headers;
  };
export type getAllWorkoutPlansDataResponseError = (
  | getAllWorkoutPlansDataResponse401
  | getAllWorkoutPlansDataResponse500
) & {
  headers: Headers;
};

export type getAllWorkoutPlansDataResponse =
  | getAllWorkoutPlansDataResponseSuccess
  | getAllWorkoutPlansDataResponseError;

export const getGetAllWorkoutPlansDataUrl = () => {
  return `/trainify/api/v1/workout-plans`;
};

export const getAllWorkoutPlansData = async (
  options?: RequestInit,
): Promise<getAllWorkoutPlansDataResponse> => {
  return customFetch<getAllWorkoutPlansDataResponse>(
    getGetAllWorkoutPlansDataUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Retorna um plano de treino
 */
export type getWorkoutPlanDetailsdDataResponse200 = {
  data: GetWorkoutPlanDetailsdData200;
  status: 200;
};

export type getWorkoutPlanDetailsdDataResponse401 = {
  data: GetWorkoutPlanDetailsdData401;
  status: 401;
};

export type getWorkoutPlanDetailsdDataResponse404 = {
  data: GetWorkoutPlanDetailsdData404;
  status: 404;
};

export type getWorkoutPlanDetailsdDataResponse500 = {
  data: GetWorkoutPlanDetailsdData500;
  status: 500;
};

export type getWorkoutPlanDetailsdDataResponseSuccess =
  getWorkoutPlanDetailsdDataResponse200 & {
    headers: Headers;
  };
export type getWorkoutPlanDetailsdDataResponseError = (
  | getWorkoutPlanDetailsdDataResponse401
  | getWorkoutPlanDetailsdDataResponse404
  | getWorkoutPlanDetailsdDataResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlanDetailsdDataResponse =
  | getWorkoutPlanDetailsdDataResponseSuccess
  | getWorkoutPlanDetailsdDataResponseError;

export const getGetWorkoutPlanDetailsdDataUrl = (id: string) => {
  return `/trainify/api/v1/workout-plans/${id}`;
};

export const getWorkoutPlanDetailsdData = async (
  id: string,
  options?: RequestInit,
): Promise<getWorkoutPlanDetailsdDataResponse> => {
  return customFetch<getWorkoutPlanDetailsdDataResponse>(
    getGetWorkoutPlanDetailsdDataUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Retorna os detalhes de um dia do plano
 */
export type getWorkoutPlanDayDetailsDataResponse200 = {
  data: GetWorkoutPlanDayDetailsData200;
  status: 200;
};

export type getWorkoutPlanDayDetailsDataResponse401 = {
  data: GetWorkoutPlanDayDetailsData401;
  status: 401;
};

export type getWorkoutPlanDayDetailsDataResponse404 = {
  data: GetWorkoutPlanDayDetailsData404;
  status: 404;
};

export type getWorkoutPlanDayDetailsDataResponse500 = {
  data: GetWorkoutPlanDayDetailsData500;
  status: 500;
};

export type getWorkoutPlanDayDetailsDataResponseSuccess =
  getWorkoutPlanDayDetailsDataResponse200 & {
    headers: Headers;
  };
export type getWorkoutPlanDayDetailsDataResponseError = (
  | getWorkoutPlanDayDetailsDataResponse401
  | getWorkoutPlanDayDetailsDataResponse404
  | getWorkoutPlanDayDetailsDataResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlanDayDetailsDataResponse =
  | getWorkoutPlanDayDetailsDataResponseSuccess
  | getWorkoutPlanDayDetailsDataResponseError;

export const getGetWorkoutPlanDayDetailsDataUrl = (
  id: string,
  dayId: string,
) => {
  return `/trainify/api/v1/workout-plans/${id}/days/${dayId}`;
};

export const getWorkoutPlanDayDetailsData = async (
  id: string,
  dayId: string,
  options?: RequestInit,
): Promise<getWorkoutPlanDayDetailsDataResponse> => {
  return customFetch<getWorkoutPlanDayDetailsDataResponse>(
    getGetWorkoutPlanDayDetailsDataUrl(id, dayId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Retorna as séries concluídas de uma sessão
 */
export type getSessionSetsResponse200 = {
  data: GetSessionSets200Item[];
  status: 200;
};

export type getSessionSetsResponse401 = {
  data: GetSessionSets401;
  status: 401;
};

export type getSessionSetsResponse404 = {
  data: GetSessionSets404;
  status: 404;
};

export type getSessionSetsResponse500 = {
  data: GetSessionSets500;
  status: 500;
};

export type getSessionSetsResponseSuccess = getSessionSetsResponse200 & {
  headers: Headers;
};
export type getSessionSetsResponseError = (
  | getSessionSetsResponse401
  | getSessionSetsResponse404
  | getSessionSetsResponse500
) & {
  headers: Headers;
};

export type getSessionSetsResponse =
  | getSessionSetsResponseSuccess
  | getSessionSetsResponseError;

export const getGetSessionSetsUrl = (
  id: string,
  dayId: string,
  sessionId: string,
) => {
  return `/trainify/api/v1/workout-plans/${id}/days/${dayId}/sessions/${sessionId}/sets`;
};

export const getSessionSets = async (
  id: string,
  dayId: string,
  sessionId: string,
  options?: RequestInit,
): Promise<getSessionSetsResponse> => {
  return customFetch<getSessionSetsResponse>(
    getGetSessionSetsUrl(id, dayId, sessionId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Marca uma série como concluída
 */
export type completeSetResponse200 = {
  data: CompleteSet200;
  status: 200;
};

export type completeSetResponse400 = {
  data: CompleteSet400;
  status: 400;
};

export type completeSetResponse401 = {
  data: CompleteSet401;
  status: 401;
};

export type completeSetResponse404 = {
  data: CompleteSet404;
  status: 404;
};

export type completeSetResponse500 = {
  data: CompleteSet500;
  status: 500;
};

export type completeSetResponseSuccess = completeSetResponse200 & {
  headers: Headers;
};
export type completeSetResponseError = (
  | completeSetResponse400
  | completeSetResponse401
  | completeSetResponse404
  | completeSetResponse500
) & {
  headers: Headers;
};

export type completeSetResponse =
  | completeSetResponseSuccess
  | completeSetResponseError;

export const getCompleteSetUrl = (
  id: string,
  dayId: string,
  sessionId: string,
  exerciseId: string,
) => {
  return `/trainify/api/v1/workout-plans/${id}/days/${dayId}/sessions/${sessionId}/exercises/${exerciseId}/sets`;
};

export const completeSet = async (
  id: string,
  dayId: string,
  sessionId: string,
  exerciseId: string,
  completeSetBody: CompleteSetBody,
  options?: RequestInit,
): Promise<completeSetResponse> => {
  return customFetch<completeSetResponse>(
    getCompleteSetUrl(id, dayId, sessionId, exerciseId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(completeSetBody),
    },
  );
};

/**
 * @summary Desmarca uma série concluída
 */
export type undoSetResponse204 = {
  data: unknown;
  status: 204;
};

export type undoSetResponse400 = {
  data: UndoSet400;
  status: 400;
};

export type undoSetResponse401 = {
  data: UndoSet401;
  status: 401;
};

export type undoSetResponse404 = {
  data: UndoSet404;
  status: 404;
};

export type undoSetResponse500 = {
  data: UndoSet500;
  status: 500;
};

export type undoSetResponseSuccess = undoSetResponse204 & {
  headers: Headers;
};
export type undoSetResponseError = (
  | undoSetResponse400
  | undoSetResponse401
  | undoSetResponse404
  | undoSetResponse500
) & {
  headers: Headers;
};

export type undoSetResponse = undoSetResponseSuccess | undoSetResponseError;

export const getUndoSetUrl = (
  id: string,
  dayId: string,
  sessionId: string,
  exerciseId: string,
) => {
  return `/trainify/api/v1/workout-plans/${id}/days/${dayId}/sessions/${sessionId}/exercises/${exerciseId}/sets`;
};

export const undoSet = async (
  id: string,
  dayId: string,
  sessionId: string,
  exerciseId: string,
  undoSetBody: UndoSetBody,
  options?: RequestInit,
): Promise<undoSetResponse> => {
  return customFetch<undoSetResponse>(
    getUndoSetUrl(id, dayId, sessionId, exerciseId),
    {
      ...options,
      method: "DELETE",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(undoSetBody),
    },
  );
};

/**
 * @summary Retorna os dados da home com base em uma data
 */
export type getHomeDataResponse200 = {
  data: GetHomeData200;
  status: 200;
};

export type getHomeDataResponse400 = {
  data: GetHomeData400;
  status: 400;
};

export type getHomeDataResponse401 = {
  data: GetHomeData401;
  status: 401;
};

export type getHomeDataResponse500 = {
  data: GetHomeData500;
  status: 500;
};

export type getHomeDataResponseSuccess = getHomeDataResponse200 & {
  headers: Headers;
};
export type getHomeDataResponseError = (
  | getHomeDataResponse400
  | getHomeDataResponse401
  | getHomeDataResponse500
) & {
  headers: Headers;
};

export type getHomeDataResponse =
  | getHomeDataResponseSuccess
  | getHomeDataResponseError;

export const getGetHomeDataUrl = (date: string) => {
  return `/trainify/api/v1/home/${date}`;
};

export const getHomeData = async (
  date: string,
  options?: RequestInit,
): Promise<getHomeDataResponse> => {
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(date), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Retorna as métricas de desempenho do usuário em um período
 */
export type getStatsDataResponse200 = {
  data: GetStatsData200;
  status: 200;
};

export type getStatsDataResponse400 = {
  data: GetStatsData400;
  status: 400;
};

export type getStatsDataResponse401 = {
  data: GetStatsData401;
  status: 401;
};

export type getStatsDataResponse500 = {
  data: GetStatsData500;
  status: 500;
};

export type getStatsDataResponseSuccess = getStatsDataResponse200 & {
  headers: Headers;
};
export type getStatsDataResponseError = (
  | getStatsDataResponse400
  | getStatsDataResponse401
  | getStatsDataResponse500
) & {
  headers: Headers;
};

export type getStatsDataResponse =
  | getStatsDataResponseSuccess
  | getStatsDataResponseError;

export const getGetStatsDataUrl = (params: GetStatsDataParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/trainify/api/v1/stats?${stringifiedParams}`
    : `/trainify/api/v1/stats`;
};

export const getStatsData = async (
  params: GetStatsDataParams,
  options?: RequestInit,
): Promise<getStatsDataResponse> => {
  return customFetch<getStatsDataResponse>(getGetStatsDataUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Retorna os dados de treino do usuário autenticado (null se não cadastrado)
 */
export type getMeResponse200 = {
  data: GetMe200;
  status: 200;
};

export type getMeResponse401 = {
  data: GetMe401;
  status: 401;
};

export type getMeResponse500 = {
  data: GetMe500;
  status: 500;
};

export type getMeResponseSuccess = getMeResponse200 & {
  headers: Headers;
};
export type getMeResponseError = (getMeResponse401 | getMeResponse500) & {
  headers: Headers;
};

export type getMeResponse = getMeResponseSuccess | getMeResponseError;

export const getGetMeUrl = () => {
  return `/trainify/api/v1/me`;
};

export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
  return customFetch<getMeResponse>(getGetMeUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Cria ou atualiza os dados de treino do usuário autenticado
 */
export type upsertTrainDataResponse200 = {
  data: UpsertTrainData200;
  status: 200;
};

export type upsertTrainDataResponse400 = {
  data: UpsertTrainData400;
  status: 400;
};

export type upsertTrainDataResponse401 = {
  data: UpsertTrainData401;
  status: 401;
};

export type upsertTrainDataResponse500 = {
  data: UpsertTrainData500;
  status: 500;
};

export type upsertTrainDataResponseSuccess = upsertTrainDataResponse200 & {
  headers: Headers;
};
export type upsertTrainDataResponseError = (
  | upsertTrainDataResponse400
  | upsertTrainDataResponse401
  | upsertTrainDataResponse500
) & {
  headers: Headers;
};

export type upsertTrainDataResponse =
  | upsertTrainDataResponseSuccess
  | upsertTrainDataResponseError;

export const getUpsertTrainDataUrl = () => {
  return `/trainify/api/v1/me/train-data`;
};

export const upsertTrainData = async (
  upsertTrainDataBody: UpsertTrainDataBody,
  options?: RequestInit,
): Promise<upsertTrainDataResponse> => {
  return customFetch<upsertTrainDataResponse>(getUpsertTrainDataUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(upsertTrainDataBody),
  });
};

/**
 * @summary Conversa com o personal trainer virtual
 */
export type chatResponse200 = {
  data: void;
  status: 200;
};

export type chatResponseSuccess = chatResponse200 & {
  headers: Headers;
};

export type chatResponse = chatResponseSuccess;

export const getChatUrl = () => {
  return `/trainify/api/v1/ai/chat`;
};

export const chat = async (
  chatBody: ChatBody,
  options?: RequestInit,
): Promise<chatResponse> => {
  return customFetch<chatResponse>(getChatUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(chatBody),
  });
};
