/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Trainify API
 * API para solução escalável para controle de planos de treino e acompanhamento físico.
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch";
/**
 * Sessão iniciada com sucesso
 */
export type StartSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  startedAt: string;
  completedAt: string | null;
};

export type StartSession400IssuesItem = {
  field: string;
  message: string;
};

/**
 * Dados inválidos
 */
export type StartSession400 = {
  statusCode: number;
  code: string;
  message: string;
  issues: StartSession400IssuesItem[];
};

/**
 * Sessão inválida ou ausente
 */
export type StartSession401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Plano ou Dia de treino não encontrado
 */
export type StartSession404 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Sessão já iniciada para o dia informado
 */
export type StartSession409 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type StartSession500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type UpdateSessionBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

/**
 * Sessão atualizada com sucesso
 */
export type UpdateSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  startedAt: string;
  completedAt: string | null;
};

export type UpdateSession400IssuesItem = {
  field: string;
  message: string;
};

/**
 * Dados inválidos
 */
export type UpdateSession400 = {
  statusCode: number;
  code: string;
  message: string;
  issues: UpdateSession400IssuesItem[];
};

/**
 * Sessão inválida ou ausente
 */
export type UpdateSession401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Plano ou Sessão de treino não encontrado(a)
 */
export type UpdateSession404 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type UpdateSession500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay];

export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  monday: "monday",
  tuesday: "tuesday",
  wednesday: "wednesday",
  thursday: "thursday",
  friday: "friday",
  saturday: "saturday",
  sunday: "sunday",
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  /** @minimum 0 */
  order: number;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 0 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay;
  isRest?: boolean;
  coverImageUrl?: string | "";
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlanBody = {
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  isActive?: boolean;
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay];

export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  monday: "monday",
  tuesday: "tuesday",
  wednesday: "wednesday",
  thursday: "thursday",
  friday: "friday",
  saturday: "saturday",
  sunday: "sunday",
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /**
   * @minLength 1
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$
   */
  id: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  /** @minimum 0 */
  order: number;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 0 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /**
   * @minLength 1
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$
   */
  id: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay;
  isRest: boolean;
  coverImageUrl?: string;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
};

/**
 * Plano de treino criado com sucesso
 */
export type CreateWorkoutPlan201 = {
  /**
   * @minLength 1
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$
   */
  id: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan400IssuesItem = {
  field: string;
  message: string;
};

/**
 * Dados inválidos
 */
export type CreateWorkoutPlan400 = {
  statusCode: number;
  code: string;
  message: string;
  issues: CreateWorkoutPlan400IssuesItem[];
};

/**
 * Sessão inválida ou ausente
 */
export type CreateWorkoutPlan401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Plano de treino não encontrado
 */
export type CreateWorkoutPlan404 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type CreateWorkoutPlan500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type FindAllWorkoutPlans200ItemWorkoutDaysItemWeekDay =
  (typeof FindAllWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof FindAllWorkoutPlans200ItemWorkoutDaysItemWeekDay];

export const FindAllWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  monday: "monday",
  tuesday: "tuesday",
  wednesday: "wednesday",
  thursday: "thursday",
  friday: "friday",
  saturday: "saturday",
  sunday: "sunday",
} as const;

export type FindAllWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /**
   * @minLength 1
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$
   */
  id: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  /** @minimum 0 */
  order: number;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 0 */
  restTimeInSeconds: number;
};

export type FindAllWorkoutPlans200ItemWorkoutDaysItem = {
  /**
   * @minLength 1
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$
   */
  id: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  weekDay: FindAllWorkoutPlans200ItemWorkoutDaysItemWeekDay;
  isRest: boolean;
  coverImageUrl?: string;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  exercises: FindAllWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
};

export type FindAllWorkoutPlans200Item = {
  /**
   * @minLength 1
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12})$
   */
  id: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  name: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  workoutDays: FindAllWorkoutPlans200ItemWorkoutDaysItem[];
};

/**
 * Sessão inválida ou ausente
 */
export type FindAllWorkoutPlans401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type FindAllWorkoutPlans500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type FindWorkoutPlanById200WorkoutDaysItemWeekDay =
  (typeof FindWorkoutPlanById200WorkoutDaysItemWeekDay)[keyof typeof FindWorkoutPlanById200WorkoutDaysItemWeekDay];

export const FindWorkoutPlanById200WorkoutDaysItemWeekDay = {
  monday: "monday",
  tuesday: "tuesday",
  wednesday: "wednesday",
  thursday: "thursday",
  friday: "friday",
  saturday: "saturday",
  sunday: "sunday",
} as const;

export type FindWorkoutPlanById200WorkoutDaysItem = {
  id: string;
  weekDay: FindWorkoutPlanById200WorkoutDaysItemWeekDay;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

/**
 * Plano de treino encontrado
 */
export type FindWorkoutPlanById200 = {
  id: string;
  name: string;
  workoutDays: FindWorkoutPlanById200WorkoutDaysItem[];
};

/**
 * Sessão inválida ou ausente
 */
export type FindWorkoutPlanById401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Plano de treino não encontrado
 */
export type FindWorkoutPlanById404 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type FindWorkoutPlanById500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type FindWorkoutPlanDayDetails200WeekDay =
  (typeof FindWorkoutPlanDayDetails200WeekDay)[keyof typeof FindWorkoutPlanDayDetails200WeekDay];

export const FindWorkoutPlanDayDetails200WeekDay = {
  monday: "monday",
  tuesday: "tuesday",
  wednesday: "wednesday",
  thursday: "thursday",
  friday: "friday",
  saturday: "saturday",
  sunday: "sunday",
} as const;

export type FindWorkoutPlanDayDetails200ExercisesItem = {
  id: string;
  name: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
  order: number;
  workoutDayId: string;
};

export type FindWorkoutPlanDayDetails200SessionsItem = {
  id: string;
  workoutDayId: string;
  startedAt?: string;
  completedAt?: string;
};

/**
 * Dia do plano retornado com sucesso
 */
export type FindWorkoutPlanDayDetails200 = {
  id: string;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  weekDay: FindWorkoutPlanDayDetails200WeekDay;
  exercises: FindWorkoutPlanDayDetails200ExercisesItem[];
  sessions: FindWorkoutPlanDayDetails200SessionsItem[];
};

/**
 * Sessão inválida ou ausente
 */
export type FindWorkoutPlanDayDetails401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Plano ou Dia de treino não encontrado
 */
export type FindWorkoutPlanDayDetails404 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type FindWorkoutPlanDayDetails500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type GetHomeData200TodayWorkoutDayWeekDay =
  (typeof GetHomeData200TodayWorkoutDayWeekDay)[keyof typeof GetHomeData200TodayWorkoutDayWeekDay];

export const GetHomeData200TodayWorkoutDayWeekDay = {
  monday: "monday",
  tuesday: "tuesday",
  wednesday: "wednesday",
  thursday: "thursday",
  friday: "friday",
  saturday: "saturday",
  sunday: "sunday",
} as const;

export type GetHomeData200TodayWorkoutDay = {
  workoutPlanId: string;
  id: string;
  name: string;
  isRest: boolean;
  weekDay: GetHomeData200TodayWorkoutDayWeekDay;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercisesCount: number;
};

export type GetHomeData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

/**
 * Dados da tela Home carregados com sucesso
 */
export type GetHomeData200 = {
  activeWorkoutPlanId: string;
  todayWorkoutDay: GetHomeData200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHomeData200ConsistencyByDay;
};

/**
 * Data inválida
 */
export type GetHomeData400 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Sessão inválida ou ausente
 */
export type GetHomeData401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type GetHomeData500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type GetStatsParams = {
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  from: string;
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  to: string;
};

export type GetStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

/**
 * Métricas carregadas com sucesso
 */
export type GetStats200 = {
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  completedWorkoutsCount: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
};

/**
 * Parâmetros de data inválidos
 */
export type GetStats400 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Sessão inválida ou ausente
 */
export type GetStats401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type GetStats500 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Dados de treino do usuário
 */
export type GetMe200 = {
  userId: string;
  userName: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
} | null;

/**
 * Sessão inválida ou ausente
 */
export type GetMe401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type GetMe500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type UpsertTrainDataBody = {
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum 0
   */
  weightInGrams: number;
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum 0
   */
  heightInCentimeters: number;
  /**
   * @minimum 1
   * @maximum 120
   */
  age: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  bodyFatPercentage: number;
};

/**
 * Dados de treino salvos com sucesso
 */
export type UpsertTrainData200 = {
  userId: string;
  userName: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
} | null;

export type UpsertTrainData400IssuesItem = {
  field: string;
  message: string;
};

/**
 * Dados inválidos
 */
export type UpsertTrainData400 = {
  statusCode: number;
  code: string;
  message: string;
  issues: UpsertTrainData400IssuesItem[];
};

/**
 * Sessão inválida ou ausente
 */
export type UpsertTrainData401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type UpsertTrainData500 = {
  statusCode: number;
  code: string;
  message: string;
};

export type ChatBodyMessagesItemRole =
  (typeof ChatBodyMessagesItemRole)[keyof typeof ChatBodyMessagesItemRole];

export const ChatBodyMessagesItemRole = {
  user: "user",
  assistant: "assistant",
} as const;

export type ChatBodyMessagesItem = {
  role: ChatBodyMessagesItemRole;
  content: string;
};

export type ChatBody = {
  /** @minItems 1 */
  messages: ChatBodyMessagesItem[];
};

/**
 * Resposta da IA
 */
export type Chat201 = {
  text: string;
};

export type Chat400IssuesItem = {
  field: string;
  message: string;
};

/**
 * Dados inválidos
 */
export type Chat400 = {
  statusCode: number;
  code: string;
  message: string;
  issues: Chat400IssuesItem[];
};

/**
 * Sessão inválida ou ausente
 */
export type Chat401 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * Erro interno do servidor
 */
export type Chat500 = {
  statusCode: number;
  code: string;
  message: string;
};

/**
 * @summary Inicia uma nova sessão de treino
 */
export type startSessionResponse201 = {
  data: StartSession201;
  status: 201;
};

export type startSessionResponse400 = {
  data: StartSession400;
  status: 400;
};

export type startSessionResponse401 = {
  data: StartSession401;
  status: 401;
};

export type startSessionResponse404 = {
  data: StartSession404;
  status: 404;
};

export type startSessionResponse409 = {
  data: StartSession409;
  status: 409;
};

export type startSessionResponse500 = {
  data: StartSession500;
  status: 500;
};

export type startSessionResponseSuccess = startSessionResponse201 & {
  headers: Headers;
};
export type startSessionResponseError = (
  | startSessionResponse400
  | startSessionResponse401
  | startSessionResponse404
  | startSessionResponse409
  | startSessionResponse500
) & {
  headers: Headers;
};

export type startSessionResponse =
  | startSessionResponseSuccess
  | startSessionResponseError;

export const getStartSessionUrl = (id: string, dayId: string) => {
  return `/trainify/api/v1/workout-plans/${id}/days/${dayId}/sessions`;
};

export const startSession = async (
  id: string,
  dayId: string,
  options?: RequestInit,
): Promise<startSessionResponse> => {
  return customFetch<startSessionResponse>(getStartSessionUrl(id, dayId), {
    ...options,
    method: "POST",
  });
};

/**
 * @summary Atualiza uma sessão de treino
 */
export type updateSessionResponse200 = {
  data: UpdateSession200;
  status: 200;
};

export type updateSessionResponse400 = {
  data: UpdateSession400;
  status: 400;
};

export type updateSessionResponse401 = {
  data: UpdateSession401;
  status: 401;
};

export type updateSessionResponse404 = {
  data: UpdateSession404;
  status: 404;
};

export type updateSessionResponse500 = {
  data: UpdateSession500;
  status: 500;
};

export type updateSessionResponseSuccess = updateSessionResponse200 & {
  headers: Headers;
};
export type updateSessionResponseError = (
  | updateSessionResponse400
  | updateSessionResponse401
  | updateSessionResponse404
  | updateSessionResponse500
) & {
  headers: Headers;
};

export type updateSessionResponse =
  | updateSessionResponseSuccess
  | updateSessionResponseError;

export const getUpdateSessionUrl = (
  id: string,
  dayId: string,
  sessionId: string,
) => {
  return `/trainify/api/v1/workout-plans/${id}/days/${dayId}/sessions/${sessionId}`;
};

export const updateSession = async (
  id: string,
  dayId: string,
  sessionId: string,
  updateSessionBody: UpdateSessionBody,
  options?: RequestInit,
): Promise<updateSessionResponse> => {
  return customFetch<updateSessionResponse>(
    getUpdateSessionUrl(id, dayId, sessionId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateSessionBody),
    },
  );
};

/**
 * @summary Cria um novo plano de treino
 */
export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlan201;
  status: 201;
};

export type createWorkoutPlanResponse400 = {
  data: CreateWorkoutPlan400;
  status: 400;
};

export type createWorkoutPlanResponse401 = {
  data: CreateWorkoutPlan401;
  status: 401;
};

export type createWorkoutPlanResponse404 = {
  data: CreateWorkoutPlan404;
  status: 404;
};

export type createWorkoutPlanResponse500 = {
  data: CreateWorkoutPlan500;
  status: 500;
};

export type createWorkoutPlanResponseSuccess = createWorkoutPlanResponse201 & {
  headers: Headers;
};
export type createWorkoutPlanResponseError = (
  | createWorkoutPlanResponse400
  | createWorkoutPlanResponse401
  | createWorkoutPlanResponse404
  | createWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type createWorkoutPlanResponse =
  | createWorkoutPlanResponseSuccess
  | createWorkoutPlanResponseError;

export const getCreateWorkoutPlanUrl = () => {
  return `/trainify/api/v1/workout-plans`;
};

export const createWorkoutPlan = async (
  createWorkoutPlanBody: CreateWorkoutPlanBody,
  options?: RequestInit,
): Promise<createWorkoutPlanResponse> => {
  return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createWorkoutPlanBody),
  });
};

/**
 * @summary Retorna todos os planos de treino
 */
export type findAllWorkoutPlansResponse200 = {
  data: FindAllWorkoutPlans200Item[];
  status: 200;
};

export type findAllWorkoutPlansResponse401 = {
  data: FindAllWorkoutPlans401;
  status: 401;
};

export type findAllWorkoutPlansResponse500 = {
  data: FindAllWorkoutPlans500;
  status: 500;
};

export type findAllWorkoutPlansResponseSuccess =
  findAllWorkoutPlansResponse200 & {
    headers: Headers;
  };
export type findAllWorkoutPlansResponseError = (
  | findAllWorkoutPlansResponse401
  | findAllWorkoutPlansResponse500
) & {
  headers: Headers;
};

export type findAllWorkoutPlansResponse =
  | findAllWorkoutPlansResponseSuccess
  | findAllWorkoutPlansResponseError;

export const getFindAllWorkoutPlansUrl = () => {
  return `/trainify/api/v1/workout-plans`;
};

export const findAllWorkoutPlans = async (
  options?: RequestInit,
): Promise<findAllWorkoutPlansResponse> => {
  return customFetch<findAllWorkoutPlansResponse>(getFindAllWorkoutPlansUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Retorna um plano de treino
 */
export type findWorkoutPlanByIdResponse200 = {
  data: FindWorkoutPlanById200;
  status: 200;
};

export type findWorkoutPlanByIdResponse401 = {
  data: FindWorkoutPlanById401;
  status: 401;
};

export type findWorkoutPlanByIdResponse404 = {
  data: FindWorkoutPlanById404;
  status: 404;
};

export type findWorkoutPlanByIdResponse500 = {
  data: FindWorkoutPlanById500;
  status: 500;
};

export type findWorkoutPlanByIdResponseSuccess =
  findWorkoutPlanByIdResponse200 & {
    headers: Headers;
  };
export type findWorkoutPlanByIdResponseError = (
  | findWorkoutPlanByIdResponse401
  | findWorkoutPlanByIdResponse404
  | findWorkoutPlanByIdResponse500
) & {
  headers: Headers;
};

export type findWorkoutPlanByIdResponse =
  | findWorkoutPlanByIdResponseSuccess
  | findWorkoutPlanByIdResponseError;

export const getFindWorkoutPlanByIdUrl = (id: string) => {
  return `/trainify/api/v1/workout-plans/${id}`;
};

export const findWorkoutPlanById = async (
  id: string,
  options?: RequestInit,
): Promise<findWorkoutPlanByIdResponse> => {
  return customFetch<findWorkoutPlanByIdResponse>(
    getFindWorkoutPlanByIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Retorna os detalhes de um dia do plano
 */
export type findWorkoutPlanDayDetailsResponse200 = {
  data: FindWorkoutPlanDayDetails200;
  status: 200;
};

export type findWorkoutPlanDayDetailsResponse401 = {
  data: FindWorkoutPlanDayDetails401;
  status: 401;
};

export type findWorkoutPlanDayDetailsResponse404 = {
  data: FindWorkoutPlanDayDetails404;
  status: 404;
};

export type findWorkoutPlanDayDetailsResponse500 = {
  data: FindWorkoutPlanDayDetails500;
  status: 500;
};

export type findWorkoutPlanDayDetailsResponseSuccess =
  findWorkoutPlanDayDetailsResponse200 & {
    headers: Headers;
  };
export type findWorkoutPlanDayDetailsResponseError = (
  | findWorkoutPlanDayDetailsResponse401
  | findWorkoutPlanDayDetailsResponse404
  | findWorkoutPlanDayDetailsResponse500
) & {
  headers: Headers;
};

export type findWorkoutPlanDayDetailsResponse =
  | findWorkoutPlanDayDetailsResponseSuccess
  | findWorkoutPlanDayDetailsResponseError;

export const getFindWorkoutPlanDayDetailsUrl = (id: string, dayId: string) => {
  return `/trainify/api/v1/workout-plans/${id}/days/${dayId}`;
};

export const findWorkoutPlanDayDetails = async (
  id: string,
  dayId: string,
  options?: RequestInit,
): Promise<findWorkoutPlanDayDetailsResponse> => {
  return customFetch<findWorkoutPlanDayDetailsResponse>(
    getFindWorkoutPlanDayDetailsUrl(id, dayId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Retorna os dados da home com base em uma data
 */
export type getHomeDataResponse200 = {
  data: GetHomeData200;
  status: 200;
};

export type getHomeDataResponse400 = {
  data: GetHomeData400;
  status: 400;
};

export type getHomeDataResponse401 = {
  data: GetHomeData401;
  status: 401;
};

export type getHomeDataResponse500 = {
  data: GetHomeData500;
  status: 500;
};

export type getHomeDataResponseSuccess = getHomeDataResponse200 & {
  headers: Headers;
};
export type getHomeDataResponseError = (
  | getHomeDataResponse400
  | getHomeDataResponse401
  | getHomeDataResponse500
) & {
  headers: Headers;
};

export type getHomeDataResponse =
  | getHomeDataResponseSuccess
  | getHomeDataResponseError;

export const getGetHomeDataUrl = (date: string) => {
  return `/trainify/api/v1/home/${date}`;
};

export const getHomeData = async (
  date: string,
  options?: RequestInit,
): Promise<getHomeDataResponse> => {
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(date), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Retorna as métricas de desempenho do usuário em um período
 */
export type getStatsResponse200 = {
  data: GetStats200;
  status: 200;
};

export type getStatsResponse400 = {
  data: GetStats400;
  status: 400;
};

export type getStatsResponse401 = {
  data: GetStats401;
  status: 401;
};

export type getStatsResponse500 = {
  data: GetStats500;
  status: 500;
};

export type getStatsResponseSuccess = getStatsResponse200 & {
  headers: Headers;
};
export type getStatsResponseError = (
  | getStatsResponse400
  | getStatsResponse401
  | getStatsResponse500
) & {
  headers: Headers;
};

export type getStatsResponse = getStatsResponseSuccess | getStatsResponseError;

export const getGetStatsUrl = (params: GetStatsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/trainify/api/v1/stats?${stringifiedParams}`
    : `/trainify/api/v1/stats`;
};

export const getStats = async (
  params: GetStatsParams,
  options?: RequestInit,
): Promise<getStatsResponse> => {
  return customFetch<getStatsResponse>(getGetStatsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Retorna os dados de treino do usuário autenticado (null se não cadastrado)
 */
export type getMeResponse200 = {
  data: GetMe200;
  status: 200;
};

export type getMeResponse401 = {
  data: GetMe401;
  status: 401;
};

export type getMeResponse500 = {
  data: GetMe500;
  status: 500;
};

export type getMeResponseSuccess = getMeResponse200 & {
  headers: Headers;
};
export type getMeResponseError = (getMeResponse401 | getMeResponse500) & {
  headers: Headers;
};

export type getMeResponse = getMeResponseSuccess | getMeResponseError;

export const getGetMeUrl = () => {
  return `/trainify/api/v1/me`;
};

export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
  return customFetch<getMeResponse>(getGetMeUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Cria ou atualiza os dados de treino do usuário autenticado
 */
export type upsertTrainDataResponse200 = {
  data: UpsertTrainData200;
  status: 200;
};

export type upsertTrainDataResponse400 = {
  data: UpsertTrainData400;
  status: 400;
};

export type upsertTrainDataResponse401 = {
  data: UpsertTrainData401;
  status: 401;
};

export type upsertTrainDataResponse500 = {
  data: UpsertTrainData500;
  status: 500;
};

export type upsertTrainDataResponseSuccess = upsertTrainDataResponse200 & {
  headers: Headers;
};
export type upsertTrainDataResponseError = (
  | upsertTrainDataResponse400
  | upsertTrainDataResponse401
  | upsertTrainDataResponse500
) & {
  headers: Headers;
};

export type upsertTrainDataResponse =
  | upsertTrainDataResponseSuccess
  | upsertTrainDataResponseError;

export const getUpsertTrainDataUrl = () => {
  return `/trainify/api/v1/me/train-data`;
};

export const upsertTrainData = async (
  upsertTrainDataBody: UpsertTrainDataBody,
  options?: RequestInit,
): Promise<upsertTrainDataResponse> => {
  return customFetch<upsertTrainDataResponse>(getUpsertTrainDataUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(upsertTrainDataBody),
  });
};

/**
 * @summary Conversa com o personal trainer virtual
 */
export type chatResponse201 = {
  data: Chat201;
  status: 201;
};

export type chatResponse400 = {
  data: Chat400;
  status: 400;
};

export type chatResponse401 = {
  data: Chat401;
  status: 401;
};

export type chatResponse500 = {
  data: Chat500;
  status: 500;
};

export type chatResponseSuccess = chatResponse201 & {
  headers: Headers;
};
export type chatResponseError = (
  | chatResponse400
  | chatResponse401
  | chatResponse500
) & {
  headers: Headers;
};

export type chatResponse = chatResponseSuccess | chatResponseError;

export const getChatUrl = () => {
  return `/trainify/api/v1/ia/chat`;
};

export const chat = async (
  chatBody: ChatBody,
  options?: RequestInit,
): Promise<chatResponse> => {
  return customFetch<chatResponse>(getChatUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(chatBody),
  });
};
